# Generated by Django 4.1.5 on 2023-01-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=150)),
            ],
        ),
    ]
