# Generated by Django 4.1.5 on 2023-01-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma_site', '0003_alter_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=2900),
        ),
    ]
