# Generated by Django 4.1.5 on 2023-01-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma_site', '0005_alter_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
